#!/bin/bash

cd ~/.config
git init
git remote add origin git@github.com:jhessin/.config 
git fetch
git reset --hard
git checkout -t origin/`hostname`

yay -Syu --noconfirm

type nvim
if [ ! $? ]; then
  yay -Sy neovim
fi

type i3lock
if [ ! $? ]; then
  yay -Sy i3lock
fi

if [ ! -e ~/.ssh/id_rsa.pub ]; then
  yay -Syy xclip
  ssh-keygen -f ~/.ssh/id_rsa -q -N ""
  eval `ssh-agent`
  ssh-add ~/.ssh/id_rsa
  cat ~/.ssh/id_rsa.pub | xclip -sel clip
  echo "Please paste SSH key into github"
  read -n1 -r -p "Press space to continue..." key
fi

type pip
if [ ! $? ]; then
  yay -Syy python-pip
  pip install --user neovim
fi

cd ~
git init
git remote add origin git@github.com:jhessin/dotfiles.git 
git fetch
git reset --hard
git checkout -t origin/master
. .bashrc

git clone git@github.com:jhessin/bin ~/.local/bin
cd ~/.local/bin
gfetch `hostname`

cd ~/.config
gfetch `hostname`
